server:
  port: 8002

spring:
  datasource:
    url: jdbc:postgresql://database-1.cq4ijmgk5u83.eu-west-2.rds.amazonaws.com:5432/users
    username: dbtestuser
    password: dbtestpassword
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show-sql: true

provider1:
  url: http://ec2-18-130-236-146.eu-west-2.compute.amazonaws.com:8081/provider1/gamelaunch
  privateKeyPath: /resources/provider1key.pem

provider2:
  url: http://ec2-18-130-236-146.eu-west-2.compute.amazonaws.com:8081/provider2/gamelaunch
  username: apiuser
  password: apipassword
