server:
  port: 8002

spring:
  datasource:
    url: jdbc:postgresql://database-1.cq4ijmgk5u83.eu-west-2.rds.amazonaws.com:5432/users
    username: dbtestuser
    password: dbtestpassword
  jpa:
    hibernate:
      ddl-auto: update